spring:
  application:
    name: gateway
  profiles:
    default: eureka-on
server:
  port: 4040

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
