version: '3.8'

services:

    db:
      image: postgres:16.1
      container_name: db-chinomarket
      restart: always
      volumes:
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        POSTGRES_DB: 'chinomarket'
        POSTGRES_USER: 'chinomarketserver'
        POSTGRES_PASSWORD: 'chinomarket2025'
      ports:
        - '5435:5432'

    registry-server:
      image: registry-server:latest
      container_name: registry-server
      ports:
        - "8761:8761"
      networks:
        - chino-net

    config-server:
      image: config-server:latest
      container_name: config-server
      depends_on:
        - registry-server
      environment:
        EUREKA_SERVER_URL: http://registry-server:8761/eureka
      ports:
        - "7777:7777"
    networks:
      - chino-net

    marketchino-master:
      image: marketchino-master:latest
      container_name: marketchino
      depends_on:
        - registry-server
        - config-server
      environment:
        EUREKA_SERVER_URL: http://registry-server:8761/eureka
      ports:
        - "8081:8081"
      networks:
        - chino-net  

    report-ms:
      image: report-ms:latest
      container_name: report
      depends_on:
        - registry-server
        - config-server
      environment:
        EUREKA_SERVER_URL: http://registry-server:8761/eureka
      ports:
        - "7070:7070"
      networks:
        - chino-net    


    auth-server:
      image: auth-server:latest
      container_name: auth-server
      depends_on:
        -registry-server
        -config-server
      environment:
        EUREKA_SERVER_URL: http://registry-server:8761/eureka
        CONFIG_SERVER_URL: http://config-server:7777
      ports:
       -"3030:3030"

    gateway:
      image: gateway:latest
      container_name: gateway
      depends_on:
        - registry-server
        - config-server
      environment:
        EUREKA_SERVER_URL: http://registry-server:8761/eureka
        CONFIG_SERVER_URL: http://config-server:7777
      ports:
        - "4040:4040"
      networks:
        - chino-net

networks:
  chino-net:
    driver: bridge    
