spring:
  profiles:
    default: default
  application:
    name: auth-server


  config:
    import: "configserver:http://localhost:7777"


  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    username: chinomarketserver
    password: chinomarket2025
    url: jdbc:postgresql://localhost:5435/chinomarket
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialize: true

server:
  port: 3030
  servlet:
    context-path: /auth-server


eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


